name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Multicast-Notification-Service-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }} 
    short_service_name: ${{ variables.short_service_name }} 
    service_base_path: ${{ variables.service_base_path }} 
    apigee_deployments:
      - environment: internal-dev
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              app_id: "73ee66da-247c-49be-8822-d23aaf4823ec"
              full: true
      - environment: internal-dev-sandbox
        proxy_path: sandbox
        post_deploy:
          - template: ./templates/run-tests.yml
      - environment: internal-qa
        post_deploy:
          # - template: ./templates/run-tests.yml No target endpoint configured for QA. Not required currently.
          #   parameters:
          #     app_id: "73ee66da-247c-49be-8822-d23aaf4823ec"
          #     full: true
      - environment: internal-qa-sandbox
        proxy_path: sandbox
        post_deploy:
          - template: ./templates/run-tests.yml
      # - environment: ref
      #   depends_on:
      #     - internal_qa
      #     - internal_qa_sandbox
      #   post_deploy:
      #     - template: ./templates/run-tests.yml
      - environment: sandbox
        proxy_path: sandbox
        # post_deploy:
        #   - template: ./templates/run-tests.yml TODO - EM-299 - is this required for sandbox?
      - environment: int
        depends_on:
          - internal_qa_sandbox
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              app_id: "0d334714-4548-4cf7-8b7f-ac194f341bc6"
              full: true
              test_command: make test-prod
      - environment: prod
        depends_on:
          - int
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              app_id: "TODO - create a test app before merging. Will need manual approval"
              full: true
              test_command: make test-prod
