name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Multicast-Notification-Service-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    prod_producer_approval: true
    apigee_deployments:
      - environment: internal-dev
        post_deploy:
          - template: ./templates/run-tests.yml
      - environment: internal-dev-sandbox
        proxy_path: sandbox
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              test_command: make smoketest
      - environment: internal-qa
      - environment: internal-qa-sandbox
        proxy_path: sandbox
      - environment: ref
        post_deploy:
          - template: ./templates/run-tests.yml
      - environment: sandbox
        proxy_path: sandbox
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              app_id: "2b969c39-f7fb-4ded-85bb-ad6571bc9eca"
              test_command: make smoketest-prod
      - environment: int
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              app_id: "64a29e72-92ca-4931-b45f-f26e5399c80c"
              test_command: make smoketest-prod
      - environment: prod
        depends_on:
          - int
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              app_id: "24c55404-2d02-403e-a57a-97ac4e4e80d9"
              test_command: make smoketest-prod
