variables:
  - group: status-endpoint
  - name: service_name
    value: multicast-notification-service
  - name: short_service_name
    value: mns
  - name: service_base_path
    value: multicast-notification-service
  - name: python_version
    value: "3.10"

