# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
specification/multicast-notification-service.yaml:
  info-license:
    - '#/info'
  no-invalid-media-type-examples:
    - "#/paths/~1events/post/requestBody/content/application~1cloudevents+json/schema"