# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
specification/multicast-notification-service.yaml:
  info-license:
    - '#/info'
