[project]
python = "^3.8"

[tool.poetry]
name = "multicast-notification-service"
version = "0.0.1-alpha"
description = "TODO"
authors = [
    #TODO add authors
]
readme = 'README.md'
license = "MIT"
repository = "https://github.com/NHSDigital/multicast-notification-service"
homepage = "https://github.com/NHSDigital/multicast-notification-service"
keywords = ["healthcare", "uk", "nhs", "events"]


[tool.poetry.dependencies]
python = "^3.8"
pytest-nhsd-apim = "^3.3.12"

[tool.poetry.dev-dependencies]
flake8 = "^5.0.4"
black = "^24.4"
pip-licenses = "^4.5.1"
jinja2 = "^3.1.4"
pyyaml = "^6.0"
docopt = "^0.6.2"
jsonpath-rw = "^1.4.0"
semver = "^3.0.4"
gitpython = "^3.1.43"
pytest = "^6.1.2"
coverage = "^7.6"
aiohttp = "^3.10.2"
pytest-asyncio = "^0.20.3"

[tool.poetry.scripts]
