# This is an OpenAPI Specification (https://swagger.io/specification/)
# for the multicast-notification-service owned by NHS Digital (https://digital.nhs.uk/)
openapi: '3.0.0'
info:
  title: 'Multicast Notification Service - REST API'
  version: 'Computed and injected at build time by `scripts/set_version.py`'
  description: |
    ## Overview
    Use this API to publish, subscribe to and receive patient-related events. The events do not contain clinical information; they simply describe what happened (the type of event) to whom and where. Where possible, a pointer will be provided in the event to retrieve the associated payload.

    You can:
      - publish events

    In future, you will be able to:
      - subscribe to events based on criteria such as NHS Number
      - receive event notifications
    ## Who can use this API
    This API can only be used where there is a legal basis to do so. Make sure you have a valid use case before you go too far with your development. You must do this before you can go live (see ‘Onboarding’ below)

    Note: during Beta, this API will only be used by NHSE product teams with a valid use case.
    ## Related APIs
    The following API also gives access to patient-related events:
      - [National Events Management Service - FHIR API](https://digital.nhs.uk/developer/api-catalogue/national-events-management-service-fhir "National Events Management Service - FHIR API")
    ## API status and roadmap
    This API is [in development](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#statuses).

    You can comment, upvote and view progress using our [roadmap](https://nhs-digital-api-management.featureupvote.com/suggestions/440034/multicast-notification-service-event-management-api).
    ## Service level
    N.A - not yet in an integration or production environment.
    ## Technology
    This API is a REST-based [publish-subscribe](https://digital.nhs.uk/developer/guides-and-documentation/introduction-to-healthcare-technology/integration-and-apis#publish-subscribe-events) API.

    The event structure is based on the recommendations of the [Cloud Events specification.](https://cloudevents.io/)
    ## Network access
    This API is available on the internet and, indirectly, on the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).

    For more details see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).
    ## Security and authorisation
    To be completed. (Will be application-based access.)
    ## Environments and testing
    To be completed.
    ## Onboarding
    To be completed.
  contact:
    name: 'multicast-notification-service API Support'
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
servers:
  - url: 'https://sandbox.api.service.nhs.uk/multicast-notification-service'
    description: Sandbox environment.
  - url: 'https://int.api.service.nhs.uk/multicast-notification-service'
    description: Integration test environment.
  - url: 'https://api.service.nhs.uk/multicast-notification-service'
    description: Production environment.
paths: {}
